name: Docker Image CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:

  test:
    runs-on: ubuntu-latest
    
    steps:
     - name: runinung tests
  
  
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Build the Docker image
      run: docker build . --file Dockerfile --tag cc-api:latest
  
  deploy:
    runs-on: ubuntu-lates
    steps:
     - name: deploy
      
